services:
  db:
    image: postgres:16
    container_name: prirtem_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prirtem_fuel
    ports:
      - "5432:5432"
    volumes:
      - prirtem_db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prirtem_app
    environment:
      PORT: 3001
      DATABASE_URL: postgres://postgres:postgres@db:5432/prirtem_fuel
      JWT_SECRET: change_me_super_secret
      APP_URL: http://localhost:3001
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  prirtem_db_data:
